### ISSUE TITLE
List issues and PRs from upstream that got resolved here 

### ISSUE THREAD

**Issue by mainrs** [go-webauthn/webauthn#2]
It would be nice to have such a list to see what has been fixed and what not. A simple list with cross-reference would be enough I guess. :) 

Just noticed that there is even a second fork you work on as well: https://github.com/authelia/webauthn
Could you explain which one is the most up-to-date? Seems like you actively contribute to all of them @james-d-elliott :D

**Comment by james-d-elliott** [comment]
Makes sense, I was intending to set this up instead of using github.com/authelia/webauthn so there was a community fork since duo seemed to lack interest in keeping the project maintained. I'm not entirely sure if I will continue since duo seemed to start maintaining it but if there is interest I can.

**Comment by james-d-elliott** [comment]
@mainrs I've compiled the list in the linked  PR/Commits. Unfortunately GitHub markdown doesn't automatically link to commit sha's, so I'll have to fix it up later, but all the information is documented. I'll leave this open for anyone else who's interested.
